# Generated by Django 5.2.6 on 2025-09-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.CharField(
                        help_text="Адрес электронной почты", max_length=100, unique=True, verbose_name="email"
                    ),
                ),
                ("full_name", models.CharField(help_text="Ф. И. О.", max_length=150, verbose_name="Ф. И. О.")),
                ("comment", models.TextField(help_text="Коментарий", verbose_name="Коментарий")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(help_text="Тема письма", max_length=250, verbose_name="Тема письма")),
                ("text", models.TextField(help_text="Тело письма", verbose_name="Тело письма")),
            ],
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "datatime_first_sending",
                    models.DateTimeField(
                        help_text="Дата и время первой отправки", verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "datetime_end_sending",
                    models.DateTimeField(
                        help_text="Дата и время окончания отправки", verbose_name="Дата и время окончания отправки"
                    ),
                ),
                ("status", models.CharField(help_text="Статус", max_length=15, verbose_name="Статус")),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="distributions", to="message.mailingrecipient", verbose_name="Получатели"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="message.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
        ),
    ]
