# Generated by Django 5.2.6 on 2025-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distribution",
            options={"ordering": ["status"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["email"],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["subject"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[("сompleted", "Завершена"), ("сreated", "Создана"), ("launched", "Запущена")],
                help_text="Статус",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
