# Generated by Django 5.2.6 on 2025-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_alter_distribution_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="datatime_first_sending",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время первой отправки",
                null=True,
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="datetime_end_sending",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время окончания отправки",
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[("сompleted", "Завершена"), ("сreated", "Создана"), ("launched", "Запущена")],
                default="Создана",
                help_text="Статус",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
