# Generated by Django 5.2.6 on 2025-09-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_alter_distribution_datatime_first_sending_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptedMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Дата и время попытки", null=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "Успешно"), ("not successful", "Не успешно")],
                        default="",
                        help_text="Статус",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(help_text="Ответ почтового сервера", verbose_name="Ответ почтового сервера"),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempted_mailing",
                        to="message.distribution",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылка",
                "verbose_name_plural": "Попытки рассылка",
                "ordering": ["status"],
            },
        ),
    ]
