# Generated by Django 5.2.6 on 2025-09-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0006_distribution_owner_message_comment_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distribution",
            options={
                "ordering": ["status"],
                "permissions": [("can_disabling_mailings_product", "can disabling mailings product")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
