# Generated by Django 5.2.6 on 2025-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0007_alter_distribution_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="mailings_status",
            field=models.BooleanField(default=False, verbose_name="Статус отключения рассылки"),
        ),
    ]
